### ISSUE TITLE
Problem as.asrtests function

### ISSUE THREAD

**Issue by FleurDamen** [briencj/asremlPlus#8]
Hi Chris,
I'm having an issue with asremlPlus since I updated to the latest version of R and RStudio. When I run the following code: as.asrtests(m_resistance2015) I get the following warning:

Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) :
invalid non-character version specification 'x' (type: double)

I have version 4.4.32 of asremlPlus, and version 4.2.0.302 of asreml.
Thanks in advance for helping me out.

Best wishes,
Fleur

**Comment by briencj** [comment]
Hi Fleur,

Sorry not to have got back to you sooner, but I was travelling overseas.

It turns out that the problem is a bug introduced by changes in R 4.4.0.

I have produced a new version of asremlPlus, 4.4.33, that fixes the problem. I will upload it to CRAN as soon as I can, but meantime you can get it from my rpackages site (http://chris.brien.name/rpackages<http://chris.brien.name/rpackages>).

Cheers,

  Chris


From: FleurDamen ***@***.***>
Sent: Friday, May 3, 2024 9:23 AM
To: briencj/asremlPlus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [briencj/asremlPlus] Problem as.asrtests function (Issue #8)

CAUTION: External email. Only click on links or open attachments from trusted senders.

________________________________
Hi Chris,
I'm having an issue with asremlPlus since I updated to the latest version of R and RStudio. When I run the following code: as.asrtests(m_resistance2015) I get the following warning:

Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) :
invalid non-character version specification 'x' (type: double)

I have version 4.4.32 of asremlPlus, and version 4.2.0.302 of asreml.
Thanks in advance for helping me out.

Best wishes,
Fleur
